device: cuda:0
root_path: /home/sasedov/StyleDomain/SimilarDomains
dataset:
  process_data: true
  processing_batch_size: 32
  dataset_size_limit: 100
  image_size: 512
  align_input: false
  dataset_path: /home/sasedov/StyleDomain/faces_dataset_small
  processed_path: /home/sasedov/StyleDomain/faces_dataset_small_processed
  inversion:
    e4e_model_path: /home/sasedov/StyleDomain/SimilarDomains/pretrained/e4e_ffhq_encode.pt
    fse_model_path: /home/sasedov/StyleDomain/SimilarDomains/pretrained/143_enc.pth
    fse_config_path: /home/sasedov/StyleDomain/SimilarDomains/FeatureStyleEncoder/configs/001.yaml
    arcface_model_path: /home/sasedov/StyleDomain/SimilarDomains/pretrained/backbone.pth
    checkpoint_path: /home/sasedov/StyleDomain/SimilarDomains/pretrained/StyleGAN2/stylegan2-ffhq-config-f.pt
    fse_idx_k: 5
